language: julia

before_install:
- echo $SSH_KEY |base64 -d -i >$HOME/.ssh/id_rsa
- chmod 600 $HOME/.ssh/id_rsa

julia:
- 1.1

cache:
  directories:
  - "$HOME/.julia"

script:
- julia --color=yes -e "using Pkg; Pkg.build(); Pkg.test(coverage=true)" && julia --color=yes docs/make.jl

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master

notifications:
  slack:
    secure: gn3tj9KRJQYCDGWsEtr0U/OMgIITKj0NqNQtyknhYpAQgWTWOidUnXitb4A5oaC8jEURSyg72wPU2O+y+E6mUuwlmDQmSY9/M+odKeEtVCQWdr7AisUo5+KRcJZXa/WkjBPm8E7uD9mZekAahCEOjPW+9amF96VJtgQMgCmaVDdH71Rgu9MZ5X/kRgiFtS3QuFhZE0JOqk1RG0VRLZuE7WPzezdSesgv+dEm+BOJhftArHGlx14A2qX+IcU0KEAYe118of7ICxnmGyDG6jjeiLpYVSAW2d5Zij3isQHnjVNqAjx9C3HvSeXieEBW4dVI1xLoNj15A/fL4VLv/hdnCqFwma9/zSBNFx74gTV6ZF+1ZrkxvvjOHC8yP3FOqFpvLGZeD/scAPozaXDTbXwNn18TFwKg8HEOj8fZVcUmrB4o4+DEhFYTIWLO9uFO+AOU8tGWt2/ES461UOtio3kpGcs2EBiz8LzDd6e8yEjoME6UgiMoggBvm1nCJV8/R10w1gVXIejkg+8ed4DGbXEv9UFAx+gRDlMk8lQ87p/3+VGDbJqubILajoqPWFTHSPMPzGu6yAjx7iGaqHT4a+l5Wz6kwCOYH+tvMJQ/HI3ZoxJi8Jlc26r+/w3eQKvzcoqlVvoxxTylSRHaZNJvOg770aT8wkzZzqP7H3b4hGibS7k=
